name: CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Backend Deploy
        run: curl -s ${{ secrets.RENDER_DEPLOY_HOOK_BACKEND }}
        
      - name: Trigger Frontend Deploy
        run: curl -s ${{ secrets.RENDER_DEPLOY_HOOK_FRONTEND }}
